# Generated by Django 2.1.2 on 2019-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20190315_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='baoming_date',
            field=models.DateField(blank=True, null=True, verbose_name='报名时间'),
        ),
    ]
