# Generated by Django 2.1.2 on 2018-11-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_userinfo_user'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
