# Generated by Django 2.1.2 on 2019-03-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_menu_permission_role_user1'),
        ('rbac', '0002_auto_20180904_1753'),
    ]

    operations = [
    ]
