# Generated by Django 2.1.2 on 2018-11-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_menu_permission_role_user1'),
        ('app01', '0002_remove_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.User1'),
        ),
    ]
