# Generated by Django 2.1.2 on 2019-03-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20181120_1955'),
        ('app01', '0002_order'),
    ]

    operations = [
    ]
